services:
  postgres:
    container_name: postgres
    image: postgres:15.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gerenciamento_de_apiario
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: